### ISSUE TITLE
What is the .xlsx used for?

### ISSUE THREAD

**Issue by oliviaguest** [themkar/SemanticsReps#1]
I noticed that the .xlsx file has some words in single quotes and some words with just a single single quote, if that makes sense! Does this matter?

**Comment by themkar** [comment]
Not at all, just put it there so you can tell to which meaning a row in the table describes.

**Comment by oliviaguest** [comment]
Ah, great. I haven't loaded these into Python yet and I assume .mat iis binary, so I will have to do this soon. I made a list of the processing steps required to get these representations on Friday in my notebook. Is it still the same pipeline of processing?

**Comment by themkar** [comment]
yes, the pipeline shown in a powerpoint I ve sent you on the 13th May. The .mat includes a table with  real numbers.

**Comment by oliviaguest** [comment]
OK, cheers.
